services:
  - type: web
    name: linkzur-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend
      npm install
      npm run build
      cd ..
      cp -r frontend/build frontend_build
      python manage.py collectstatic --noinput
    startCommand: gunicorn Linkzur_backend.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.10
