# Generated by Django 5.2.4 on 2025-07-30 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkzur_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_type',
            new_name='role',
        ),
    ]
