# Generated by Django 5.2.7 on 2025-10-19 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkzur_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_discount',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_est_price',
            new_name='est_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_hsn',
            new_name='hsn',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_refno',
            new_name='ref_no',
        ),
    ]
