# Generated by Django 5.2.8 on 2025-11-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkzur_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('chemicals', 'Chemicals'), ('instruments', 'Instruments'), ('consumables', 'Consumables'), ('ppe', 'PPE'), ('edevices', 'E-Devices'), ('glassware', 'Glassware'), ('biologics', 'Biologics'), ('solvents', 'Solvents'), ('books_stationery', 'Books & Stationery'), ('furniture', 'Furniture')], max_length=50),
        ),
    ]
