# Generated by Django 5.2.8 on 2025-11-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkzur_app', '0004_billingaddress_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivered_verified',
            field=models.BooleanField(default=False),
        ),
    ]
