# Generated by Django 5.2.8 on 2025-11-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkzur_app', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
