# Generated by Django 5.2.8 on 2025-12-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkzur_app', '0008_recentlyviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
